# 开发环境配置
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://10.1.2.230:3306/data_acquisition?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: data_acquisition
    password: G1e86czRd5ttZVlV

  data:
    redis:
      host: 10.1.2.230
      port: 6379
      password: 6WJHKT8ahxYDOFwF

minio:
  endpoint: http://10.1.2.230:9000
  accessKey: 65RD1skNPDqG
  secretKey: 9VQaHWcHU27t2tYC

dingtalk:
  app-key: dingy7l8pfsax5fcpixx
  app-secret: tWLyh7H4qXDqFKCuyr43WYwYQlX0iTUnWNimPgvBRrd6xxR37C4WNKl4MGpRO2-e
  agent-id: 4428808319
  corp-id: dinge1e6e6ade9b4593e35c2f4657eb6378f
  sync:
    enabled: ${DINGTALK_SYNC_ENABLED:true}
    cron: "0 0 2 * * ?"

logging:
  level:
    com.dataacquisition: debug
