-- 设备调研表
CREATE TABLE IF NOT EXISTS `t_device_research` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `device_id` BIGINT DEFAULT NULL COMMENT '关联设备ID',
  `device_code` VARCHAR(100) DEFAULT NULL COMMENT '设备编号',
  `device_name` VARCHAR(200) DEFAULT NULL COMMENT '设备名称',
  `project_id` BIGINT DEFAULT NULL COMMENT '所属项目ID',
  `project_name` VARCHAR(200) DEFAULT NULL COMMENT '项目名称',
  `device_type` VARCHAR(100) DEFAULT NULL COMMENT '设备类型',
  `workshop` VARCHAR(100) DEFAULT NULL COMMENT '所属车间',
  `quantity` INT DEFAULT 1 COMMENT '数量',
  `device_manufacturer` VARCHAR(200) DEFAULT NULL COMMENT '设备厂商',
  `is_interface_occupied` TINYINT(1) DEFAULT NULL COMMENT '控制器接口被占用',
  `interface_type` VARCHAR(20) DEFAULT NULL COMMENT '控制器接口类型(serial/network)',
  `has_touch_screen` TINYINT(1) DEFAULT NULL COMMENT '连接触摸屏',
  `controller_brand` VARCHAR(100) DEFAULT NULL COMMENT '控制器品牌',
  `controller_model` VARCHAR(100) DEFAULT NULL COMMENT '控制器型号',
  `touch_screen_brand` VARCHAR(100) DEFAULT NULL COMMENT '触摸屏品牌',
  `has_point_table` TINYINT(1) DEFAULT NULL COMMENT '是否提供点位表',
  `has_plc_source` TINYINT(1) DEFAULT NULL COMMENT '是否提供PLC源程序',
  `has_touch_screen_source` TINYINT(1) DEFAULT NULL COMMENT '是否提供触摸屏源程序',
  `controller_photos` TEXT DEFAULT NULL COMMENT '控制器照片(JSON数组)',
  `controller_videos` TEXT DEFAULT NULL COMMENT '控制器视频(JSON数组)',
  `touchscreen_photos` TEXT DEFAULT NULL COMMENT '触摸屏照片(JSON数组)',
  `touchscreen_videos` TEXT DEFAULT NULL COMMENT '触摸屏视频(JSON数组)',
  `cabinet_photos` TEXT DEFAULT NULL COMMENT '控制柜照片(JSON数组)',
  `cabinet_videos` TEXT DEFAULT NULL COMMENT '控制柜视频(JSON数组)',
  `collect_device_status` TINYINT(1) DEFAULT NULL COMMENT '采集设备状态',
  `collect_process_params` TINYINT(1) DEFAULT NULL COMMENT '采集工艺参数',
  `data_items` TEXT DEFAULT NULL COMMENT '需采集数据项(JSON数组)',
  `data_items_detail` TEXT DEFAULT NULL COMMENT '需采集数据项明细',
  `collect_production` TINYINT(1) DEFAULT NULL COMMENT '采集产量/节拍',
  `collect_energy` TINYINT(1) DEFAULT NULL COMMENT '采集能耗',
  `basic_completed` TINYINT(1) DEFAULT 0 COMMENT '基础信息是否完成',
  `controller_completed` TINYINT(1) DEFAULT 0 COMMENT '控制器信息是否完成',
  `collection_completed` TINYINT(1) DEFAULT 0 COMMENT '采集信息是否完成',
  `research_progress` INT DEFAULT 0 COMMENT '调研进度(0-100)',
  `researcher_id` BIGINT DEFAULT NULL COMMENT '调研人员ID',
  `researcher_name` VARCHAR(100) DEFAULT NULL COMMENT '调研人员姓名',
  `research_date` DATE DEFAULT NULL COMMENT '调研日期',
  `remarks` TEXT DEFAULT NULL COMMENT '备注',
  `created_by` BIGINT DEFAULT NULL COMMENT '创建人ID',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT DEFAULT NULL COMMENT '更新人ID',
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT DEFAULT 0 COMMENT '删除标记(0=未删除,1=已删除)',
  PRIMARY KEY (`id`),
  KEY `idx_device_id` (`device_id`),
  KEY `idx_project_id` (`project_id`),
  KEY `idx_workshop` (`workshop`),
  KEY `idx_device_type` (`device_type`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='设备调研表';
